server:
  port: 8888
  
spring:
  application:
    name: CLOUD_CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pravatjana91/config-server
          clone-on-start: true
          
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
    
