server:
    port: 8080
    
spring:
    application:
        name: MYBATIS-SERVICE
    config:
      import: optional:configserver:http://localhost:8889
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
        
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
    type-aliases-package: com.td.mybatismicroservice.dto
